/**
 * @packageDocumentation
 * @module api.functional.account.mfa.backup_codes.regenerate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { IBackupCodesRegenerateResponse } from "../../../../../../../apps/server/src/modules/IRIS-account/dtos/mfa.dto";

/**
 * Generates a fresh set of 10 single-use emergency backup codes.
 *
 * @returns New emergency backup codes.
 *
 * @controller AccountMfaController.regenerateBackupCodes
 * @path POST /account/mfa/backup-codes/regenerate
 * @accessor api.functional.account.mfa.backup_codes.regenerate.regenerateBackupCodes
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function regenerateBackupCodes(
  connection: IConnection,
): Promise<regenerateBackupCodes.Output> {
  return true === connection.simulate
    ? regenerateBackupCodes.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...regenerateBackupCodes.METADATA,
        template: regenerateBackupCodes.METADATA.path,
        path: regenerateBackupCodes.path(),
      });
}
export namespace regenerateBackupCodes {
  export type Output = Primitive<IBackupCodesRegenerateResponse>;

  export const METADATA = {
    method: "POST",
    path: "/account/mfa/backup-codes/regenerate",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/account/mfa/backup-codes/regenerate";
  export const random = (): Resolved<
    Primitive<IBackupCodesRegenerateResponse>
  > => typia.random<Primitive<IBackupCodesRegenerateResponse>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
