/**
 * @packageDocumentation
 * @module api.functional.auth.passkey.register_options
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { IPasskeyRegisterOptionsResponse } from "../../../../../../apps/server/src/modules/IRIS-account/dtos/passkey.dto";

/**
 * Generates WebAuthn registration challenge options for an authenticated user.
 *
 * @returns Registration options for `navigator.credentials.create()`.
 * @throws 404 User not found.
 *
 * @controller AuthPasskeyController.getRegisterOptions
 * @path POST /auth/passkey/register-options
 * @accessor api.functional.auth.passkey.register_options.getRegisterOptions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getRegisterOptions(
  connection: IConnection,
): Promise<getRegisterOptions.Output> {
  return true === connection.simulate
    ? getRegisterOptions.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getRegisterOptions.METADATA,
        template: getRegisterOptions.METADATA.path,
        path: getRegisterOptions.path(),
      });
}
export namespace getRegisterOptions {
  export type Output = Primitive<IPasskeyRegisterOptionsResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/passkey/register-options",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/passkey/register-options";
  export const random = (): Resolved<
    Primitive<IPasskeyRegisterOptionsResponse>
  > => typia.random<Primitive<IPasskeyRegisterOptionsResponse>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
