kind: pipeline
type: docker
name: default

# services:
#   - name: IRIS-database
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: IRIS-dev
#     ports:
#       - 5432

#   - name: IRIS-cache
#     image: redis:latest
#     ports:
#       - 6379

steps:
  - name: Environment
    image: node:22-alpine
    environment:
      ENV_FILE:
        from_secret: ENV_FILE
    commands:
      - apk add --no-cache libc6-compat openssl
      - echo "$ENV_FILE" > .env
      - corepack enable
      - pnpm install --frozen-lockfile

  - name: Prisma push
    image: node:22-alpine
    commands:
      - apk add --no-cache libc6-compat openssl
      - corepack enable
      - pnpm db:push

  - name: Prisma generate
    image: node:22-alpine
    commands:
      - apk add --no-cache libc6-compat openssl
      - corepack enable
      - pnpm db:generate

  - name: Elysia build
    image: oven/bun:1-alpine
    commands:
      - bun run route:sync

  - name: Build packages
    image: node:22-alpine
    commands:
      - apk add --no-cache libc6-compat openssl
      - corepack enable
      - pnpm build:packages

  - name: Web build
    image: node:22-alpine
    environment:
      NODE_ENV: production
    commands:
      - corepack enable
      - pnpm --filter web build

  - name: Cleanup
    image: node:22-alpine
    commands:
      - rm -rf .turbo node_modules/.cache
