packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msw: false
  prisma: true
  sharp: true
  unrs-resolver: true
