/**
 * Comprehensive set of reserved language keywords, SQL keywords, and system routes
 * that cannot be used as usernames to avoid collisions and injection risks.
 */
export const RESERVED_KEYWORDS = new Set<string>([
  // JavaScript & TypeScript keywords
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "let",
  "package",
  "private",
  "protected",
  "public",
  "static",
  "any",
  "boolean",
  "constructor",
  "declare",
  "get",
  "module",
  "require",
  "number",
  "set",
  "string",
  "symbol",
  "type",
  "undefined",
  "unknown",
  "never",
  "readonly",
  "keyof",
  "infer",
  "as",
  "from",
  "of",
  "namespace",
  "interface",
  "implements",
  "enum",
  "await",

  // SQL keywords
  "select",
  "insert",
  "update",
  "drop",
  "truncate",
  "alter",
  "create",
  "table",
  "database",
  "index",
  "use",
  "where",
  "join",
  "left",
  "right",
  "inner",
  "outer",
  "on",
  "and",
  "or",
  "not",
  "union",
  "values",
  "into",
  "order",
  "by",
  "group",
  "having",
  "limit",
  "offset",
  "distinct",
  "all",
  "exists",
  "like",
  "between",
  "is",

  // System & Application routes
  "admin",
  "administrator",
  "root",
  "system",
  "sysadmin",
  "moderator",
  "mod",
  "owner",
  "support",
  "security",
  "help",
  "contact",
  "info",
  "billing",
  "api",
  "auth",
  "oauth",
  "login",
  "logout",
  "signin",
  "signout",
  "signup",
  "register",
  "settings",
  "account",
  "profile",
  "dashboard",
  "iris",
  "polaris",
  "runa",
  "runerra",
  "null",
  "undefined",
  "anonymous",
  "guest",
  "bot",
  "webhook",
  "static",
  "assets",
  "public",
]);

/**
 * Checks if a given username is in the reserved keywords blacklist.
 * Normalizes input by trimming and converting to lower-case.
 *
 * @param username - Username string to evaluate.
 * @returns `true` if reserved, `false` otherwise.
 */
export function isReservedKeyword(username: string): boolean {
  if (!username) return false;
  return RESERVED_KEYWORDS.has(username.trim().toLowerCase());
}
