import type { ComponentPresetItem } from "./types"
import { createSectionPreset } from "../../ast-utils"

export const sectionPresets: ComponentPresetItem[] = [
  {
    id: "section-12-col",
    name: "12-Column Grid (All 12 Column Slots)",
    category: "sections",
    icon: "IconLayoutGrid",
    description: "True 12-column grid with 12 distinct column slots across the entire screen width",
    getNode: () => createSectionPreset("12-col-grid"),
  },
  {
    id: "section-3-zone",
    name: "3-Zone Canvas (3 / 6 / 3 Cols)",
    category: "sections",
    icon: "IconColumns",
    description: "App layout with left rail (3 cols), center canvas (6 cols), and right panel (3 cols)",
    getNode: () => createSectionPreset("3-zone-canvas"),
  },
  {
    id: "section-4-col",
    name: "4-Column Grid (3 Cols Each)",
    category: "sections",
    icon: "IconLayoutGrid",
    description: "4 equal layout columns across the screen (3 + 3 + 3 + 3 = 12 cols)",
    getNode: () => createSectionPreset("4-col-grid"),
  },
  {
    id: "section-3-col",
    name: "3-Column Grid (4 Cols Each)",
    category: "sections",
    icon: "IconColumns",
    description: "3 equal layout columns across the screen (4 + 4 + 4 = 12 cols)",
    getNode: () => createSectionPreset("3-col"),
  },
  {
    id: "section-2-col",
    name: "2-Column Split (6 Cols Each)",
    category: "sections",
    icon: "IconLayoutColumns",
    description: "2 responsive 50/50 layout columns (6 + 6 = 12 cols)",
    getNode: () => createSectionPreset("2-col"),
  },
  {
    id: "section-sidebar-canvas",
    name: "Sidebar + Main Canvas (3 / 9 Cols)",
    category: "sections",
    icon: "IconLayoutSidebar",
    description: "App workspace with fixed 3-column navigation and wide 9-column content canvas",
    getNode: () => createSectionPreset("sidebar-canvas"),
  },
  {
    id: "section-fluid",
    name: "Fluid Edge-to-Edge Container",
    category: "sections",
    icon: "IconArrowsMaximize",
    description: "100% full viewport width container without horizontal clamping",
    getNode: () => createSectionPreset("fluid-full"),
  },
  {
    id: "section-1-col",
    name: "1-Column Section",
    category: "sections",
    icon: "IconLayout",
    description: "Full-width section with 1 centered layout item",
    getNode: () => createSectionPreset("1-col"),
  },
  {
    id: "section-hero",
    name: "Hero Banner",
    category: "sections",
    icon: "IconSparkles",
    description: "Centered hero banner with title, subtitle, and CTA buttons",
    getNode: () => createSectionPreset("hero"),
  },
  {
    id: "section-card-grid",
    name: "Card Grid",
    category: "sections",
    icon: "IconCards",
    description: "3 feature cards in a responsive grid",
    getNode: () => createSectionPreset("card-grid"),
  },
]
