/**
 * @packageDocumentation
 * @module api.functional.auth.code.status
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  ILoginCodeStatusQuery,
  ILoginCodeStatusResponse,
} from "../../../../../../apps/server/src/modules/IRIS-account/dtos/code.dto";

/**
 * Polled by the requesting device to check authorization status.
 *
 * @param query - Query containing the polling session token.
 * @returns Current status and session credentials if approved.
 *
 * @controller AuthCodeController.getStatus
 * @path GET /auth/code/status
 * @accessor api.functional.auth.code.status.getStatus
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getStatus(
  connection: IConnection,
  query: getStatus.Query,
): Promise<getStatus.Output> {
  return true === connection.simulate
    ? getStatus.simulate(connection, query)
    : PlainFetcher.fetch(connection, {
        ...getStatus.METADATA,
        template: getStatus.METADATA.path,
        path: getStatus.path(query),
      });
}
export namespace getStatus {
  export type Query = Resolved<ILoginCodeStatusQuery>;
  export type Output = Primitive<ILoginCodeStatusResponse>;

  export const METADATA = {
    method: "GET",
    path: "/auth/code/status",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/auth/code/status";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Primitive<ILoginCodeStatusResponse>> =>
    typia.random<Primitive<ILoginCodeStatusResponse>>();
  export const simulate = (connection: IConnection, query: Query): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(query),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(query));
    return random();
  };
}
