/**
 * @packageDocumentation
 * @module api.functional.auth.password.forgot
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  IPasswordForgotRequest,
  ISuccessResponse,
} from "../../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";

/**
 * Sends password recovery instructions to the specified email address.
 *
 * @param body - Email address payload.
 * @returns Success acknowledgment.
 *
 * @controller AuthController.forgotPassword
 * @path POST /auth/password/forgot
 * @accessor api.functional.auth.password.forgot.forgotPassword
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function forgotPassword(
  connection: IConnection,
  body: forgotPassword.Body,
): Promise<forgotPassword.Output> {
  return true === connection.simulate
    ? forgotPassword.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...forgotPassword.METADATA,
          template: forgotPassword.METADATA.path,
          path: forgotPassword.path(),
        },
        body,
      );
}
export namespace forgotPassword {
  export type Body = Primitive<IPasswordForgotRequest>;
  export type Output = Primitive<ISuccessResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/password/forgot",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/password/forgot";
  export const random = (): Resolved<Primitive<ISuccessResponse>> =>
    typia.random<Primitive<ISuccessResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
