/**
 * @packageDocumentation
 * @module api.functional.account.mfa.backup_codes
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as regenerate from "./regenerate/index";
