/**
 * @packageDocumentation
 * @module api.functional.account.mfa.totp
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as setup from "./setup/index";
export * as enable from "./enable/index";
export * as disable from "./disable/index";
