/**
 * @packageDocumentation
 * @module api.functional.account.mfa.totp.setup
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ITotpSetupResponse } from "../../../../../../../apps/server/src/modules/IRIS-account/dtos/mfa.dto";

/**
 * Generates a new TOTP secret key and QR code data URL for enrollment.
 *
 * @returns TOTP setup data.
 *
 * @controller AccountMfaController.setupTotp
 * @path POST /account/mfa/totp/setup
 * @accessor api.functional.account.mfa.totp.setup.setupTotp
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function setupTotp(
  connection: IConnection,
): Promise<setupTotp.Output> {
  return true === connection.simulate
    ? setupTotp.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...setupTotp.METADATA,
        template: setupTotp.METADATA.path,
        path: setupTotp.path(),
      });
}
export namespace setupTotp {
  export type Output = Primitive<ITotpSetupResponse>;

  export const METADATA = {
    method: "POST",
    path: "/account/mfa/totp/setup",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/account/mfa/totp/setup";
  export const random = (): Resolved<Primitive<ITotpSetupResponse>> =>
    typia.random<Primitive<ITotpSetupResponse>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
