/**
 * @packageDocumentation
 * @module api.functional.auth.passkey.register_verify
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ISuccessResponse } from "../../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";
import type { IPasskeyRegisterVerifyRequest } from "../../../../../../apps/server/src/modules/IRIS-account/dtos/passkey.dto";

/**
 * Verifies and registers a new passkey.
 *
 * @param body - Attestation response and label.
 * @returns Success acknowledgment.
 * @throws 400 Passkey registration verification failed.
 * @throws 401 Passkey registration challenge has expired.
 *
 * @controller AuthPasskeyController.verifyRegister
 * @path POST /auth/passkey/register-verify
 * @accessor api.functional.auth.passkey.register_verify.verifyRegister
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function verifyRegister(
  connection: IConnection,
  body: verifyRegister.Body,
): Promise<verifyRegister.Output> {
  return true === connection.simulate
    ? verifyRegister.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...verifyRegister.METADATA,
          template: verifyRegister.METADATA.path,
          path: verifyRegister.path(),
        },
        body,
      );
}
export namespace verifyRegister {
  export type Body = Primitive<IPasskeyRegisterVerifyRequest>;
  export type Output = Primitive<ISuccessResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/passkey/register-verify",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/passkey/register-verify";
  export const random = (): Resolved<Primitive<ISuccessResponse>> =>
    typia.random<Primitive<ISuccessResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
