/**
 * @packageDocumentation
 * @module api.functional.auth.code.approve
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ISuccessResponse } from "../../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";
import type { ILoginCodeApproveRequest } from "../../../../../../apps/server/src/modules/IRIS-account/dtos/code.dto";

/**
 * Approves a quick-connect code from an authenticated device.
 *
 * @param body - Code to approve.
 * @returns Success acknowledgment.
 * @throws 404 Login code is invalid or has expired.
 *
 * @controller AuthCodeController.approveCode
 * @path POST /auth/code/approve
 * @accessor api.functional.auth.code.approve.approveCode
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function approveCode(
  connection: IConnection,
  body: approveCode.Body,
): Promise<approveCode.Output> {
  return true === connection.simulate
    ? approveCode.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...approveCode.METADATA,
          template: approveCode.METADATA.path,
          path: approveCode.path(),
        },
        body,
      );
}
export namespace approveCode {
  export type Body = Primitive<ILoginCodeApproveRequest>;
  export type Output = Primitive<ISuccessResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/code/approve",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/code/approve";
  export const random = (): Resolved<Primitive<ISuccessResponse>> =>
    typia.random<Primitive<ISuccessResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
