/**
 * @packageDocumentation
 * @module api.functional.account.mfa.verify
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ILoginResponse } from "../../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";
import type { IMfaVerifyRequest } from "../../../../../../apps/server/src/modules/IRIS-account/dtos/mfa.dto";

/**
 * Verifies an MFA challenge token (TOTP, Email OTP, or emergency backup code) to complete login.
 *
 * @param body - Verification parameters.
 * @returns Complete login session.
 * @throws 400 Specified MFA method is not active for this account.
 * @throws 401 Invalid verification code or MFA ticket expired.
 * @throws 404 User not found.
 *
 * @controller AccountMfaController.verifyMfa
 * @path POST /account/mfa/verify
 * @accessor api.functional.account.mfa.verify.verifyMfa
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function verifyMfa(
  connection: IConnection,
  body: verifyMfa.Body,
): Promise<verifyMfa.Output> {
  return true === connection.simulate
    ? verifyMfa.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...verifyMfa.METADATA,
          template: verifyMfa.METADATA.path,
          path: verifyMfa.path(),
        },
        body,
      );
}
export namespace verifyMfa {
  export type Body = Primitive<IMfaVerifyRequest>;
  export type Output = Primitive<ILoginResponse>;

  export const METADATA = {
    method: "POST",
    path: "/account/mfa/verify",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/account/mfa/verify";
  export const random = (): Resolved<Primitive<ILoginResponse>> =>
    typia.random<Primitive<ILoginResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
