/**
 * @packageDocumentation
 * @module api.functional.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  ILoginRequest,
  ILoginResponse,
  IRegisterRequest,
  IRegisterResponse,
} from "../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";

export * as passkey from "./passkey/index";
export * as code from "./code/index";
export * as password from "./password/index";

/**
 * Authenticates user with username or email and plaintext password.
 *
 * @param body - Credentials payload.
 * @returns Successful login session or MFA challenge requirements.
 * @throws 401 Invalid username, email, or password.
 *
 * @controller AuthController.login
 * @path POST /auth/login
 * @accessor api.functional.auth.login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  body: login.Body,
): Promise<login.Output> {
  return true === connection.simulate
    ? login.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...login.METADATA,
          template: login.METADATA.path,
          path: login.path(),
        },
        body,
      );
}
export namespace login {
  export type Body = Primitive<ILoginRequest>;
  export type Output = Primitive<ILoginResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/login";
  export const random = (): Resolved<Primitive<ILoginResponse>> =>
    typia.random<Primitive<ILoginResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}

/**
 * Creates a new user account with salted password hash and encrypted Ed25519 keypair.
 *
 * @param body - Registration payload.
 * @returns Created user summary and public key.
 * @throws 400 Password or username does not meet complexity requirements.
 * @throws 409 Username is already taken or email is in use.
 *
 * @controller AuthController.register
 * @path POST /auth/register
 * @accessor api.functional.auth.register
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function register(
  connection: IConnection,
  body: register.Body,
): Promise<register.Output> {
  return true === connection.simulate
    ? register.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...register.METADATA,
          template: register.METADATA.path,
          path: register.path(),
        },
        body,
      );
}
export namespace register {
  export type Body = Primitive<IRegisterRequest>;
  export type Output = Primitive<IRegisterResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/register",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/register";
  export const random = (): Resolved<Primitive<IRegisterResponse>> =>
    typia.random<Primitive<IRegisterResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
