/**
 * @packageDocumentation
 * @module api.functional.auth.passkey.login_options
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  IPasskeyLoginOptionsRequest,
  IPasskeyLoginOptionsResponse,
} from "../../../../../../apps/server/src/modules/IRIS-account/dtos/passkey.dto";

/**
 * Generates WebAuthn authentication challenge options for passkey login.
 *
 * @param body - Optional identifier.
 * @returns Challenge options for `navigator.credentials.get()`.
 *
 * @controller AuthPasskeyController.getLoginOptions
 * @path POST /auth/passkey/login-options
 * @accessor api.functional.auth.passkey.login_options.getLoginOptions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLoginOptions(
  connection: IConnection,
  body: getLoginOptions.Body,
): Promise<getLoginOptions.Output> {
  return true === connection.simulate
    ? getLoginOptions.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getLoginOptions.METADATA,
          template: getLoginOptions.METADATA.path,
          path: getLoginOptions.path(),
        },
        body,
      );
}
export namespace getLoginOptions {
  export type Body = Primitive<IPasskeyLoginOptionsRequest>;
  export type Output = Primitive<IPasskeyLoginOptionsResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/passkey/login-options",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/passkey/login-options";
  export const random = (): Resolved<Primitive<IPasskeyLoginOptionsResponse>> =>
    typia.random<Primitive<IPasskeyLoginOptionsResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
