/**
 * @packageDocumentation
 * @module api.functional.auth.code.generate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  ILoginCodeGenerateRequest,
  ILoginCodeGenerateResponse,
} from "../../../../../../apps/server/src/modules/IRIS-account/dtos/code.dto";

/**
 * Generates a 6-character quick-connect code and QR session token with 5-minute TTL.
 *
 * @param body - Request options including optional device name.
 * @returns Generated code and QR session payload.
 *
 * @controller AuthCodeController.generateCode
 * @path POST /auth/code/generate
 * @accessor api.functional.auth.code.generate.generateCode
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function generateCode(
  connection: IConnection,
  body: generateCode.Body,
): Promise<generateCode.Output> {
  return true === connection.simulate
    ? generateCode.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...generateCode.METADATA,
          template: generateCode.METADATA.path,
          path: generateCode.path(),
        },
        body,
      );
}
export namespace generateCode {
  export type Body = Primitive<ILoginCodeGenerateRequest>;
  export type Output = Primitive<ILoginCodeGenerateResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/code/generate",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/code/generate";
  export const random = (): Resolved<Primitive<ILoginCodeGenerateResponse>> =>
    typia.random<Primitive<ILoginCodeGenerateResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
