/**
 * @packageDocumentation
 * @module api.functional.account.mfa.totp.disable
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ISuccessResponse } from "../../../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";
import type { ITotpDisableRequest } from "../../../../../../../apps/server/src/modules/IRIS-account/dtos/mfa.dto";

/**
 * Disables TOTP on the user's account after confirming their password.
 *
 * @param body - Password confirmation.
 * @returns Success acknowledgment.
 * @throws 401 Incorrect password.
 * @throws 404 User not found.
 *
 * @controller AccountMfaController.disableTotp
 * @path POST /account/mfa/totp/disable
 * @accessor api.functional.account.mfa.totp.disable.disableTotp
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function disableTotp(
  connection: IConnection,
  body: disableTotp.Body,
): Promise<disableTotp.Output> {
  return true === connection.simulate
    ? disableTotp.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...disableTotp.METADATA,
          template: disableTotp.METADATA.path,
          path: disableTotp.path(),
        },
        body,
      );
}
export namespace disableTotp {
  export type Body = Primitive<ITotpDisableRequest>;
  export type Output = Primitive<ISuccessResponse>;

  export const METADATA = {
    method: "POST",
    path: "/account/mfa/totp/disable",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/account/mfa/totp/disable";
  export const random = (): Resolved<Primitive<ISuccessResponse>> =>
    typia.random<Primitive<ISuccessResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
