/**
 * @packageDocumentation
 * @module api.functional.account.mfa.email.send_code
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ISuccessResponse } from "../../../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";
import type { IMfaSendEmailCodeRequest } from "../../../../../../../apps/server/src/modules/IRIS-account/dtos/mfa.dto";

/**
 * Dispatches a 6-digit email OTP verification code to the user's registered email during login.
 *
 * @param body - MFA challenge ticket.
 * @returns Success acknowledgment.
 * @throws 401 MFA ticket has expired or is invalid.
 * @throws 404 User not found.
 *
 * @controller AccountMfaController.sendEmailMfaCode
 * @path POST /account/mfa/email/send-code
 * @accessor api.functional.account.mfa.email.send_code.sendEmailMfaCode
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function sendEmailMfaCode(
  connection: IConnection,
  body: sendEmailMfaCode.Body,
): Promise<sendEmailMfaCode.Output> {
  return true === connection.simulate
    ? sendEmailMfaCode.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...sendEmailMfaCode.METADATA,
          template: sendEmailMfaCode.METADATA.path,
          path: sendEmailMfaCode.path(),
        },
        body,
      );
}
export namespace sendEmailMfaCode {
  export type Body = Primitive<IMfaSendEmailCodeRequest>;
  export type Output = Primitive<ISuccessResponse>;

  export const METADATA = {
    method: "POST",
    path: "/account/mfa/email/send-code",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/account/mfa/email/send-code";
  export const random = (): Resolved<Primitive<ISuccessResponse>> =>
    typia.random<Primitive<ISuccessResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
