/**
 * @packageDocumentation
 * @module api.functional.auth.password
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as change from "./change/index";
export * as forgot from "./forgot/index";
export * as reset from "./reset/index";
