/**
 * @packageDocumentation
 * @module api.functional.account.mfa.totp.enable
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  ITotpEnableRequest,
  ITotpEnableResponse,
} from "../../../../../../../apps/server/src/modules/IRIS-account/dtos/mfa.dto";

/**
 * Confirms initial TOTP setup with a code from the authenticator app and returns backup codes.
 *
 * @param body - 6-digit confirmation code.
 * @returns Enablement status and backup codes.
 * @throws 400 Invalid authenticator code or setup session expired.
 *
 * @controller AccountMfaController.enableTotp
 * @path POST /account/mfa/totp/enable
 * @accessor api.functional.account.mfa.totp.enable.enableTotp
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function enableTotp(
  connection: IConnection,
  body: enableTotp.Body,
): Promise<enableTotp.Output> {
  return true === connection.simulate
    ? enableTotp.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...enableTotp.METADATA,
          template: enableTotp.METADATA.path,
          path: enableTotp.path(),
        },
        body,
      );
}
export namespace enableTotp {
  export type Body = Primitive<ITotpEnableRequest>;
  export type Output = Primitive<ITotpEnableResponse>;

  export const METADATA = {
    method: "POST",
    path: "/account/mfa/totp/enable",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/account/mfa/totp/enable";
  export const random = (): Resolved<Primitive<ITotpEnableResponse>> =>
    typia.random<Primitive<ITotpEnableResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
