/* eslint-disable */
// Automatically generated by the IRIS file router for cache key type safety.
// Do not edit manually.

export interface GlobalCacheKeys {
  anime: {
    id: (id: number) => string;
  };
  book: {
    id: (id: number) => string;
  };
  game: {
    id: (id: number) => string;
  };
  manga: {
    id: (id: number) => string;
  };
  movie: {
    id: (id: number) => string;
  };
  music: {
    id: (id: number) => string;
  };
  tv: {
    id: (id: number) => string;
  };
}

export type GlobalCacheKeyStorage = GlobalCacheKeys;
