/* eslint-disable */
// Automatically generated by the IRIS file router for cache key type safety.
// Do not edit manually.

export interface GlobalCacheKeys {
  anime: {
    id: (id: number) => string;
  };
  book: {
    id: (id: number) => string;
  };
  game: {
    id: (id: number) => string;
  };
  manga: {
    id: (id: number) => string;
  };
  movie: {
    id: (id: number) => string;
  };
  music: {
    id: (id: number) => string;
  };
  search: {
    anime: (q: string) => string;
    books: (q: string) => string;
    characters: (q: string) => string;
    games: (q: string) => string;
    manga: (q: string) => string;
    movies: (q: string) => string;
    music: (q: string) => string;
    people: (q: string) => string;
    studios: (q: string) => string;
    tv: (q: string) => string;
  };
  similar: {
    anime: (id: number) => string;
    books: (id: number) => string;
    games: (id: number) => string;
    manga: (id: number) => string;
    movies: (id: number) => string;
    music: (id: number) => string;
    tv: (id: number) => string;
  };
  tv: {
    id: (id: number) => string;
  };
}

export type GlobalCacheKeyStorage = GlobalCacheKeys;
