/* eslint-disable */
// Automatically generated by the IRIS file router for Eden Treaty.
// Do not edit manually.
import { Elysia } from "elysia";
import { executeWithRequestLogs } from "../utils/request-logger";
import { createRateLimiter } from "../plugins/rate-limiter";
import route_0 from "../modules/IRIS-account/user/[id]/list/route";

const routeLimiters = new Map<string, ReturnType<typeof createRateLimiter>>();
function getRouteLimiter(key: string, config: unknown) {
  let l = routeLimiters.get(key);
  if (!l) {
    l = createRateLimiter(config as any);
    routeLimiters.set(key, l);
  }
  return l;
}

export const routes = new Elysia({ name: "iris-routes" })
  .get("/health", () => ({
    status: "ok",
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
  }))
  .get(
    "/user/:id/list",
    ((route_0 as any).GET?.schema ?? (route_0 as any).schemas?.GET ?? (route_0 as any).schema)!,
    async (ctx) => {
      const methodItem = (route_0 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_0 as any).rateLimits?.GET ?? (route_0 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_0_GET", rateLimitConfig) : null;
      return executeWithRequestLogs(ctx, handler, limiter);
    }
  );

export type App = typeof routes;
