/* eslint-disable */
// Automatically generated by the IRIS file router for Eden Treaty.
// Do not edit manually.
import { Elysia } from "elysia";
import { executeWithRequestLogs } from "../utils/request-logger";
import { createRateLimiter } from "../plugins/rate-limiter";
import route_0 from "../modules/IRIS-account/auth/api-keys/[id]/regenerate/route";
import route_1 from "../modules/IRIS-account/auth/api-keys/[id]/route";
import route_2 from "../modules/IRIS-account/auth/api-keys/route";
import route_3 from "../modules/IRIS-account/auth/backupcodes/regenerate/route";
import route_4 from "../modules/IRIS-account/auth/email/send/route";
import route_5 from "../modules/IRIS-account/auth/email/toggle/route";
import route_6 from "../modules/IRIS-account/auth/email/verify/route";
import route_7 from "../modules/IRIS-account/auth/login/route";
import route_8 from "../modules/IRIS-account/auth/passkeys/[id]/route";
import route_9 from "../modules/IRIS-account/auth/passkeys/login/route";
import route_10 from "../modules/IRIS-account/auth/passkeys/login/verify/route";
import route_11 from "../modules/IRIS-account/auth/passkeys/register/route";
import route_12 from "../modules/IRIS-account/auth/passkeys/register/verify/route";
import route_13 from "../modules/IRIS-account/auth/passkeys/route";
import route_14 from "../modules/IRIS-account/auth/password/change/route";
import route_15 from "../modules/IRIS-account/auth/password/forgot/route";
import route_16 from "../modules/IRIS-account/auth/password/reset/route";
import route_17 from "../modules/IRIS-account/auth/quickconnect/approve/route";
import route_18 from "../modules/IRIS-account/auth/quickconnect/generate/route";
import route_19 from "../modules/IRIS-account/auth/quickconnect/status/route";
import route_20 from "../modules/IRIS-account/auth/register/route";
import route_21 from "../modules/IRIS-account/auth/totp/setup/route";
import route_22 from "../modules/IRIS-account/auth/totp/toggle/route";
import route_23 from "../modules/IRIS-account/notifications/[id]/action/route";
import route_24 from "../modules/IRIS-account/notifications/[id]/read/route";
import route_25 from "../modules/IRIS-account/notifications/[id]/route";
import route_26 from "../modules/IRIS-account/notifications/mark-all-read/route";
import route_27 from "../modules/IRIS-account/notifications/route";
import route_28 from "../modules/IRIS-account/public/[...key]/route";
import route_29 from "../modules/IRIS-account/users/me/assets/route";
import route_30 from "../modules/IRIS-account/users/me/encryption/route";
import route_31 from "../modules/IRIS-account/users/me/route";
import route_32 from "../modules/IRIS-connections/connections/[id]/auth/route";
import route_33 from "../modules/IRIS-connections/connections/[id]/callback/route";
import route_34 from "../modules/IRIS-connections/connections/[id]/route";
import route_35 from "../modules/IRIS-connections/connections/[id]/sync/route";
import route_36 from "../modules/IRIS-connections/connections/[id]/test/route";
import route_37 from "../modules/IRIS-connections/connections/providers/route";
import route_38 from "../modules/IRIS-connections/connections/route";
import route_39 from "../modules/IRIS-connections/connections/search/route";
import route_40 from "../modules/IRIS-list/user/[username]/favorites/[id]/route";
import route_41 from "../modules/IRIS-list/user/[username]/favorites/route";
import route_42 from "../modules/IRIS-list/user/[username]/lists/anime/[id]/route";
import route_43 from "../modules/IRIS-list/user/[username]/lists/anime/route";
import route_44 from "../modules/IRIS-list/user/[username]/lists/books/[id]/route";
import route_45 from "../modules/IRIS-list/user/[username]/lists/books/route";
import route_46 from "../modules/IRIS-list/user/[username]/lists/games/[id]/route";
import route_47 from "../modules/IRIS-list/user/[username]/lists/games/route";
import route_48 from "../modules/IRIS-list/user/[username]/lists/manga/[id]/route";
import route_49 from "../modules/IRIS-list/user/[username]/lists/manga/route";
import route_50 from "../modules/IRIS-list/user/[username]/lists/movies/[id]/route";
import route_51 from "../modules/IRIS-list/user/[username]/lists/movies/route";
import route_52 from "../modules/IRIS-list/user/[username]/lists/music/[id]/route";
import route_53 from "../modules/IRIS-list/user/[username]/lists/music/route";
import route_54 from "../modules/IRIS-list/user/[username]/lists/tv/[id]/route";
import route_55 from "../modules/IRIS-list/user/[username]/lists/tv/route";
import route_56 from "../modules/IRIS-list/user/[username]/watchlists/[id]/entries/route";
import route_57 from "../modules/IRIS-list/user/[username]/watchlists/[id]/route";
import route_58 from "../modules/IRIS-list/user/[username]/watchlists/route";
import route_59 from "../modules/IRIS-media/media/anime/[id]/refresh/route";
import route_60 from "../modules/IRIS-media/media/anime/[id]/route";
import route_61 from "../modules/IRIS-media/media/anime/[id]/similar/route";
import route_62 from "../modules/IRIS-media/media/books/[id]/refresh/route";
import route_63 from "../modules/IRIS-media/media/books/[id]/route";
import route_64 from "../modules/IRIS-media/media/books/[id]/similar/route";
import route_65 from "../modules/IRIS-media/media/characters/[id]/route";
import route_66 from "../modules/IRIS-media/media/games/[id]/refresh/route";
import route_67 from "../modules/IRIS-media/media/games/[id]/route";
import route_68 from "../modules/IRIS-media/media/games/[id]/similar/route";
import route_69 from "../modules/IRIS-media/media/manga/[id]/refresh/route";
import route_70 from "../modules/IRIS-media/media/manga/[id]/route";
import route_71 from "../modules/IRIS-media/media/manga/[id]/similar/route";
import route_72 from "../modules/IRIS-media/media/movies/[id]/refresh/route";
import route_73 from "../modules/IRIS-media/media/movies/[id]/route";
import route_74 from "../modules/IRIS-media/media/movies/[id]/similar/route";
import route_75 from "../modules/IRIS-media/media/music/[id]/refresh/route";
import route_76 from "../modules/IRIS-media/media/music/[id]/route";
import route_77 from "../modules/IRIS-media/media/music/[id]/similar/route";
import route_78 from "../modules/IRIS-media/media/people/[id]/route";
import route_79 from "../modules/IRIS-media/media/studios/[id]/route";
import route_80 from "../modules/IRIS-media/media/tv/[id]/refresh/route";
import route_81 from "../modules/IRIS-media/media/tv/[id]/route";
import route_82 from "../modules/IRIS-media/media/tv/[id]/similar/route";
import route_83 from "../modules/IRIS-media/search/anime/route";
import route_84 from "../modules/IRIS-media/search/books/route";
import route_85 from "../modules/IRIS-media/search/characters/route";
import route_86 from "../modules/IRIS-media/search/games/route";
import route_87 from "../modules/IRIS-media/search/manga/route";
import route_88 from "../modules/IRIS-media/search/movies/route";
import route_89 from "../modules/IRIS-media/search/music/route";
import route_90 from "../modules/IRIS-media/search/people/route";
import route_91 from "../modules/IRIS-media/search/studios/route";
import route_92 from "../modules/IRIS-media/search/tv/route";
import route_93 from "../modules/IRIS-social/recommendations/[id]/route";
import route_94 from "../modules/IRIS-social/recommendations/[id]/vote/route";
import route_95 from "../modules/IRIS-social/recommendations/[type]/[id]/route";
import route_96 from "../modules/IRIS-social/recommendations/route";
import route_97 from "../modules/IRIS-social/reviews/[type]/[id]/route";
import route_98 from "../modules/IRIS-social/reviews/[type]/[id]/vote/route";
import route_99 from "../modules/IRIS-social/user/[username]/reviews/route";

const routeLimiters = new Map<string, ReturnType<typeof createRateLimiter>>();
function getRouteLimiter(key: string, config: unknown) {
  let l = routeLimiters.get(key);
  if (!l) {
    l = createRateLimiter(config as any);
    routeLimiters.set(key, l);
  }
  return l;
}

export const globalCacheKeyStorage: Record<string, Record<string, any>> = {};
function deepMergeCacheKeys(target: Record<string, any>, source: Record<string, any>) {
  for (const [key, val] of Object.entries(source)) {
    if (typeof val === "function") {
      target[key] = val;
    } else if (val && typeof val === "object") {
      if (!target[key] || typeof target[key] !== "object") {
        target[key] = {};
      }
      deepMergeCacheKeys(target[key], val);
    }
  }
}
if ((route_60 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_60 as any).cacheKeys);
}
if ((route_61 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_61 as any).cacheKeys);
}
if ((route_63 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_63 as any).cacheKeys);
}
if ((route_64 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_64 as any).cacheKeys);
}
if ((route_67 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_67 as any).cacheKeys);
}
if ((route_68 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_68 as any).cacheKeys);
}
if ((route_70 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_70 as any).cacheKeys);
}
if ((route_71 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_71 as any).cacheKeys);
}
if ((route_73 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_73 as any).cacheKeys);
}
if ((route_74 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_74 as any).cacheKeys);
}
if ((route_76 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_76 as any).cacheKeys);
}
if ((route_77 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_77 as any).cacheKeys);
}
if ((route_81 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_81 as any).cacheKeys);
}
if ((route_82 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_82 as any).cacheKeys);
}
if ((route_83 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_83 as any).cacheKeys);
}
if ((route_84 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_84 as any).cacheKeys);
}
if ((route_85 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_85 as any).cacheKeys);
}
if ((route_86 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_86 as any).cacheKeys);
}
if ((route_87 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_87 as any).cacheKeys);
}
if ((route_88 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_88 as any).cacheKeys);
}
if ((route_89 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_89 as any).cacheKeys);
}
if ((route_90 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_90 as any).cacheKeys);
}
if ((route_91 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_91 as any).cacheKeys);
}
if ((route_92 as any)?.cacheKeys) {
  deepMergeCacheKeys(globalCacheKeyStorage, (route_92 as any).cacheKeys);
}

export const routes = new Elysia({ name: "iris-routes" })
  .get("/health", () => ({
    status: "ok",
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
  }))
  .post(
    "/auth/api-keys/:id/regenerate",
    route_0.POST!.schema,
    async (ctx: any) => {
      const methodItem = (route_0 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_0 as any).rateLimits?.POST ?? (route_0 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_0_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/auth/api-keys/:id",
    route_1.DELETE!.schema,
    async (ctx: any) => {
      const methodItem = (route_1 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_1 as any).rateLimits?.DELETE ?? (route_1 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_1_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .patch(
    "/auth/api-keys/:id",
    route_1.PATCH!.schema,
    async (ctx: any) => {
      const methodItem = (route_1 as any).PATCH;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_1 as any).rateLimits?.PATCH ?? (route_1 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_1_PATCH", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/auth/api-keys",
    route_2.GET!.schema,
    async (ctx: any) => {
      const methodItem = (route_2 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_2 as any).rateLimits?.GET ?? (route_2 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_2_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/api-keys",
    route_2.POST!.schema,
    async (ctx: any) => {
      const methodItem = (route_2 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_2 as any).rateLimits?.POST ?? (route_2 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_2_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/backupcodes/regenerate",
    route_3.schema,
    async (ctx: any) => {
      const methodItem = (route_3 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_3 as any).rateLimits?.POST ?? (route_3 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_3_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/email/send",
    route_4.schema,
    async (ctx: any) => {
      const methodItem = (route_4 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_4 as any).rateLimits?.POST ?? (route_4 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_4_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/email/toggle",
    route_5.schema,
    async (ctx: any) => {
      const methodItem = (route_5 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_5 as any).rateLimits?.POST ?? (route_5 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_5_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/email/verify",
    route_6.schema,
    async (ctx: any) => {
      const methodItem = (route_6 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_6 as any).rateLimits?.POST ?? (route_6 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_6_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/login",
    route_7.schema,
    async (ctx: any) => {
      const methodItem = (route_7 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_7 as any).rateLimits?.POST ?? (route_7 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_7_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/auth/passkeys/:id",
    route_8.schema,
    async (ctx: any) => {
      const methodItem = (route_8 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_8 as any).rateLimits?.DELETE ?? (route_8 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_8_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/passkeys/login",
    route_9.schema,
    async (ctx: any) => {
      const methodItem = (route_9 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_9 as any).rateLimits?.POST ?? (route_9 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_9_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/passkeys/login/verify",
    route_10.schema,
    async (ctx: any) => {
      const methodItem = (route_10 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_10 as any).rateLimits?.POST ?? (route_10 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_10_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/passkeys/register",
    route_11.schema,
    async (ctx: any) => {
      const methodItem = (route_11 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_11 as any).rateLimits?.POST ?? (route_11 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_11_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/passkeys/register/verify",
    route_12.schema,
    async (ctx: any) => {
      const methodItem = (route_12 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_12 as any).rateLimits?.POST ?? (route_12 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_12_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/auth/passkeys",
    route_13.schema,
    async (ctx: any) => {
      const methodItem = (route_13 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_13 as any).rateLimits?.GET ?? (route_13 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_13_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/password/change",
    route_14.schema,
    async (ctx: any) => {
      const methodItem = (route_14 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_14 as any).rateLimits?.POST ?? (route_14 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_14_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/password/forgot",
    route_15.schema,
    async (ctx: any) => {
      const methodItem = (route_15 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_15 as any).rateLimits?.POST ?? (route_15 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_15_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/password/reset",
    route_16.schema,
    async (ctx: any) => {
      const methodItem = (route_16 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_16 as any).rateLimits?.POST ?? (route_16 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_16_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/quickconnect/approve",
    route_17.schema,
    async (ctx: any) => {
      const methodItem = (route_17 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_17 as any).rateLimits?.POST ?? (route_17 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_17_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/quickconnect/generate",
    route_18.schema,
    async (ctx: any) => {
      const methodItem = (route_18 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_18 as any).rateLimits?.POST ?? (route_18 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_18_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/auth/quickconnect/status",
    route_19.schema,
    async (ctx: any) => {
      const methodItem = (route_19 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_19 as any).rateLimits?.GET ?? (route_19 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_19_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/register",
    route_20.schema,
    async (ctx: any) => {
      const methodItem = (route_20 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_20 as any).rateLimits?.POST ?? (route_20 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_20_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/totp/setup",
    route_21.schema,
    async (ctx: any) => {
      const methodItem = (route_21 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_21 as any).rateLimits?.POST ?? (route_21 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_21_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/auth/totp/toggle",
    route_22.schema,
    async (ctx: any) => {
      const methodItem = (route_22 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_22 as any).rateLimits?.POST ?? (route_22 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_22_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/notifications/:id/action",
    route_23.POST!.schema,
    async (ctx: any) => {
      const methodItem = (route_23 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_23 as any).rateLimits?.POST ?? (route_23 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_23_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .patch(
    "/notifications/:id/read",
    route_24.PATCH!.schema,
    async (ctx: any) => {
      const methodItem = (route_24 as any).PATCH;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_24 as any).rateLimits?.PATCH ?? (route_24 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_24_PATCH", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/notifications/:id",
    route_25.GET!.schema,
    async (ctx: any) => {
      const methodItem = (route_25 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_25 as any).rateLimits?.GET ?? (route_25 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_25_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/notifications/:id",
    route_25.DELETE!.schema,
    async (ctx: any) => {
      const methodItem = (route_25 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_25 as any).rateLimits?.DELETE ?? (route_25 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_25_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/notifications/mark-all-read",
    route_26.POST!.schema,
    async (ctx: any) => {
      const methodItem = (route_26 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_26 as any).rateLimits?.POST ?? (route_26 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_26_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/notifications",
    route_27.GET!.schema,
    async (ctx: any) => {
      const methodItem = (route_27 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_27 as any).rateLimits?.GET ?? (route_27 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_27_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/notifications",
    route_27.DELETE!.schema,
    async (ctx: any) => {
      const methodItem = (route_27 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_27 as any).rateLimits?.DELETE ?? (route_27 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_27_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/public/*",
    async (ctx: any) => {
      const methodItem = (route_28 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_28 as any).rateLimits?.GET ?? (route_28 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_28_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/users/me/assets",
    route_29.POST!.schema,
    async (ctx: any) => {
      const methodItem = (route_29 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_29 as any).rateLimits?.POST ?? (route_29 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_29_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/users/me/assets",
    route_29.DELETE!.schema,
    async (ctx: any) => {
      const methodItem = (route_29 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_29 as any).rateLimits?.DELETE ?? (route_29 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_29_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/users/me/encryption",
    route_30.GET!.schema,
    async (ctx: any) => {
      const methodItem = (route_30 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_30 as any).rateLimits?.GET ?? (route_30 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_30_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/users/me/encryption",
    route_30.POST!.schema,
    async (ctx: any) => {
      const methodItem = (route_30 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_30 as any).rateLimits?.POST ?? (route_30 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_30_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/users/me",
    route_31.GET!.schema,
    async (ctx: any) => {
      const methodItem = (route_31 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_31 as any).rateLimits?.GET ?? (route_31 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_31_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .patch(
    "/users/me",
    route_31.PATCH!.schema,
    async (ctx: any) => {
      const methodItem = (route_31 as any).PATCH;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_31 as any).rateLimits?.PATCH ?? (route_31 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_31_PATCH", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/connections/:id/auth",
    route_32.GET!.schema,
    async (ctx: any) => {
      const methodItem = (route_32 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_32 as any).rateLimits?.GET ?? (route_32 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_32_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/connections/:id/callback",
    route_33.GET!.schema,
    async (ctx: any) => {
      const methodItem = (route_33 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_33 as any).rateLimits?.GET ?? (route_33 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_33_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/connections/:id",
    route_34.DELETE!.schema,
    async (ctx: any) => {
      const methodItem = (route_34 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_34 as any).rateLimits?.DELETE ?? (route_34 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_34_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .patch(
    "/connections/:id",
    route_34.PATCH!.schema,
    async (ctx: any) => {
      const methodItem = (route_34 as any).PATCH;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_34 as any).rateLimits?.PATCH ?? (route_34 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_34_PATCH", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/connections/:id/sync",
    route_35.POST!.schema,
    async (ctx: any) => {
      const methodItem = (route_35 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_35 as any).rateLimits?.POST ?? (route_35 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_35_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/connections/:id/test",
    route_36.POST!.schema,
    async (ctx: any) => {
      const methodItem = (route_36 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_36 as any).rateLimits?.POST ?? (route_36 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_36_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/connections/providers",
    route_37.GET!.schema,
    async (ctx: any) => {
      const methodItem = (route_37 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_37 as any).rateLimits?.GET ?? (route_37 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_37_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/connections",
    route_38.GET!.schema,
    async (ctx: any) => {
      const methodItem = (route_38 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_38 as any).rateLimits?.GET ?? (route_38 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_38_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/connections",
    route_38.POST!.schema,
    async (ctx: any) => {
      const methodItem = (route_38 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_38 as any).rateLimits?.POST ?? (route_38 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_38_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/connections/search",
    route_39.GET!.schema,
    async (ctx: any) => {
      const methodItem = (route_39 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_39 as any).rateLimits?.GET ?? (route_39 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_39_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/favorites/:id",
    route_40.schema,
    async (ctx: any) => {
      const methodItem = (route_40 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_40 as any).rateLimits?.GET ?? (route_40 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_40_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/user/:username/favorites/:id",
    route_40.schema,
    async (ctx: any) => {
      const methodItem = (route_40 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_40 as any).rateLimits?.POST ?? (route_40 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_40_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/user/:username/favorites/:id",
    route_40.schema,
    async (ctx: any) => {
      const methodItem = (route_40 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_40 as any).rateLimits?.DELETE ?? (route_40 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_40_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/favorites",
    route_41.schema,
    async (ctx: any) => {
      const methodItem = (route_41 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_41 as any).rateLimits?.GET ?? (route_41 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_41_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/anime/:id",
    route_42.schema,
    async (ctx: any) => {
      const methodItem = (route_42 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_42 as any).rateLimits?.GET ?? (route_42 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_42_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/user/:username/lists/anime/:id",
    route_42.schema,
    async (ctx: any) => {
      const methodItem = (route_42 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_42 as any).rateLimits?.POST ?? (route_42 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_42_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/user/:username/lists/anime/:id",
    route_42.schema,
    async (ctx: any) => {
      const methodItem = (route_42 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_42 as any).rateLimits?.DELETE ?? (route_42 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_42_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/anime",
    route_43.schema,
    async (ctx: any) => {
      const methodItem = (route_43 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_43 as any).rateLimits?.GET ?? (route_43 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_43_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/books/:id",
    route_44.schema,
    async (ctx: any) => {
      const methodItem = (route_44 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_44 as any).rateLimits?.GET ?? (route_44 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_44_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/user/:username/lists/books/:id",
    route_44.schema,
    async (ctx: any) => {
      const methodItem = (route_44 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_44 as any).rateLimits?.POST ?? (route_44 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_44_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/user/:username/lists/books/:id",
    route_44.schema,
    async (ctx: any) => {
      const methodItem = (route_44 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_44 as any).rateLimits?.DELETE ?? (route_44 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_44_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/books",
    route_45.schema,
    async (ctx: any) => {
      const methodItem = (route_45 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_45 as any).rateLimits?.GET ?? (route_45 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_45_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/games/:id",
    route_46.schema,
    async (ctx: any) => {
      const methodItem = (route_46 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_46 as any).rateLimits?.GET ?? (route_46 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_46_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/user/:username/lists/games/:id",
    route_46.schema,
    async (ctx: any) => {
      const methodItem = (route_46 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_46 as any).rateLimits?.POST ?? (route_46 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_46_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/user/:username/lists/games/:id",
    route_46.schema,
    async (ctx: any) => {
      const methodItem = (route_46 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_46 as any).rateLimits?.DELETE ?? (route_46 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_46_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/games",
    route_47.schema,
    async (ctx: any) => {
      const methodItem = (route_47 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_47 as any).rateLimits?.GET ?? (route_47 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_47_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/manga/:id",
    route_48.schema,
    async (ctx: any) => {
      const methodItem = (route_48 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_48 as any).rateLimits?.GET ?? (route_48 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_48_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/user/:username/lists/manga/:id",
    route_48.schema,
    async (ctx: any) => {
      const methodItem = (route_48 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_48 as any).rateLimits?.POST ?? (route_48 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_48_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/user/:username/lists/manga/:id",
    route_48.schema,
    async (ctx: any) => {
      const methodItem = (route_48 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_48 as any).rateLimits?.DELETE ?? (route_48 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_48_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/manga",
    route_49.schema,
    async (ctx: any) => {
      const methodItem = (route_49 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_49 as any).rateLimits?.GET ?? (route_49 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_49_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/movies/:id",
    route_50.schema,
    async (ctx: any) => {
      const methodItem = (route_50 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_50 as any).rateLimits?.GET ?? (route_50 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_50_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/user/:username/lists/movies/:id",
    route_50.schema,
    async (ctx: any) => {
      const methodItem = (route_50 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_50 as any).rateLimits?.POST ?? (route_50 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_50_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/user/:username/lists/movies/:id",
    route_50.schema,
    async (ctx: any) => {
      const methodItem = (route_50 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_50 as any).rateLimits?.DELETE ?? (route_50 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_50_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/movies",
    route_51.schema,
    async (ctx: any) => {
      const methodItem = (route_51 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_51 as any).rateLimits?.GET ?? (route_51 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_51_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/music/:id",
    route_52.schema,
    async (ctx: any) => {
      const methodItem = (route_52 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_52 as any).rateLimits?.GET ?? (route_52 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_52_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/user/:username/lists/music/:id",
    route_52.schema,
    async (ctx: any) => {
      const methodItem = (route_52 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_52 as any).rateLimits?.POST ?? (route_52 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_52_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/user/:username/lists/music/:id",
    route_52.schema,
    async (ctx: any) => {
      const methodItem = (route_52 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_52 as any).rateLimits?.DELETE ?? (route_52 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_52_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/music",
    route_53.schema,
    async (ctx: any) => {
      const methodItem = (route_53 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_53 as any).rateLimits?.GET ?? (route_53 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_53_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/tv/:id",
    route_54.schema,
    async (ctx: any) => {
      const methodItem = (route_54 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_54 as any).rateLimits?.GET ?? (route_54 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_54_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/user/:username/lists/tv/:id",
    route_54.schema,
    async (ctx: any) => {
      const methodItem = (route_54 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_54 as any).rateLimits?.POST ?? (route_54 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_54_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/user/:username/lists/tv/:id",
    route_54.schema,
    async (ctx: any) => {
      const methodItem = (route_54 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_54 as any).rateLimits?.DELETE ?? (route_54 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_54_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/lists/tv",
    route_55.schema,
    async (ctx: any) => {
      const methodItem = (route_55 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_55 as any).rateLimits?.GET ?? (route_55 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_55_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/user/:username/watchlists/:id/entries",
    route_56.schema,
    async (ctx: any) => {
      const methodItem = (route_56 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_56 as any).rateLimits?.POST ?? (route_56 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_56_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/user/:username/watchlists/:id/entries",
    route_56.schema,
    async (ctx: any) => {
      const methodItem = (route_56 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_56 as any).rateLimits?.DELETE ?? (route_56 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_56_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/watchlists/:id",
    route_57.schema,
    async (ctx: any) => {
      const methodItem = (route_57 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_57 as any).rateLimits?.GET ?? (route_57 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_57_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/user/:username/watchlists/:id",
    route_57.schema,
    async (ctx: any) => {
      const methodItem = (route_57 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_57 as any).rateLimits?.DELETE ?? (route_57 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_57_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .patch(
    "/user/:username/watchlists/:id",
    route_57.schema,
    async (ctx: any) => {
      const methodItem = (route_57 as any).PATCH;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_57 as any).rateLimits?.PATCH ?? (route_57 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_57_PATCH", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/watchlists",
    route_58.schema,
    async (ctx: any) => {
      const methodItem = (route_58 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_58 as any).rateLimits?.GET ?? (route_58 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_58_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/user/:username/watchlists",
    route_58.schema,
    async (ctx: any) => {
      const methodItem = (route_58 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_58 as any).rateLimits?.POST ?? (route_58 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_58_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/media/anime/:id/refresh",
    route_59.schema,
    async (ctx: any) => {
      const methodItem = (route_59 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_59 as any).rateLimits?.POST ?? (route_59 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_59_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/anime/:id",
    route_60.schema,
    async (ctx: any) => {
      const methodItem = (route_60 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_60 as any).rateLimits?.GET ?? (route_60 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_60_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/anime/:id/similar",
    route_61.schema,
    async (ctx: any) => {
      const methodItem = (route_61 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_61 as any).rateLimits?.GET ?? (route_61 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_61_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/media/books/:id/refresh",
    route_62.schema,
    async (ctx: any) => {
      const methodItem = (route_62 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_62 as any).rateLimits?.POST ?? (route_62 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_62_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/books/:id",
    route_63.schema,
    async (ctx: any) => {
      const methodItem = (route_63 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_63 as any).rateLimits?.GET ?? (route_63 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_63_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/books/:id/similar",
    route_64.schema,
    async (ctx: any) => {
      const methodItem = (route_64 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_64 as any).rateLimits?.GET ?? (route_64 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_64_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/characters/:id",
    route_65.schema,
    async (ctx: any) => {
      const methodItem = (route_65 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_65 as any).rateLimits?.GET ?? (route_65 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_65_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/media/games/:id/refresh",
    route_66.schema,
    async (ctx: any) => {
      const methodItem = (route_66 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_66 as any).rateLimits?.POST ?? (route_66 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_66_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/games/:id",
    route_67.schema,
    async (ctx: any) => {
      const methodItem = (route_67 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_67 as any).rateLimits?.GET ?? (route_67 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_67_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/games/:id/similar",
    route_68.schema,
    async (ctx: any) => {
      const methodItem = (route_68 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_68 as any).rateLimits?.GET ?? (route_68 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_68_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/media/manga/:id/refresh",
    route_69.schema,
    async (ctx: any) => {
      const methodItem = (route_69 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_69 as any).rateLimits?.POST ?? (route_69 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_69_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/manga/:id",
    route_70.schema,
    async (ctx: any) => {
      const methodItem = (route_70 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_70 as any).rateLimits?.GET ?? (route_70 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_70_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/manga/:id/similar",
    route_71.schema,
    async (ctx: any) => {
      const methodItem = (route_71 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_71 as any).rateLimits?.GET ?? (route_71 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_71_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/media/movies/:id/refresh",
    route_72.schema,
    async (ctx: any) => {
      const methodItem = (route_72 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_72 as any).rateLimits?.POST ?? (route_72 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_72_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/movies/:id",
    route_73.schema,
    async (ctx: any) => {
      const methodItem = (route_73 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_73 as any).rateLimits?.GET ?? (route_73 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_73_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/movies/:id/similar",
    route_74.schema,
    async (ctx: any) => {
      const methodItem = (route_74 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_74 as any).rateLimits?.GET ?? (route_74 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_74_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/media/music/:id/refresh",
    route_75.schema,
    async (ctx: any) => {
      const methodItem = (route_75 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_75 as any).rateLimits?.POST ?? (route_75 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_75_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/music/:id",
    route_76.schema,
    async (ctx: any) => {
      const methodItem = (route_76 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_76 as any).rateLimits?.GET ?? (route_76 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_76_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/music/:id/similar",
    route_77.schema,
    async (ctx: any) => {
      const methodItem = (route_77 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_77 as any).rateLimits?.GET ?? (route_77 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_77_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/people/:id",
    route_78.schema,
    async (ctx: any) => {
      const methodItem = (route_78 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_78 as any).rateLimits?.GET ?? (route_78 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_78_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/studios/:id",
    route_79.schema,
    async (ctx: any) => {
      const methodItem = (route_79 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_79 as any).rateLimits?.GET ?? (route_79 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_79_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/media/tv/:id/refresh",
    route_80.schema,
    async (ctx: any) => {
      const methodItem = (route_80 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_80 as any).rateLimits?.POST ?? (route_80 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_80_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/tv/:id",
    route_81.schema,
    async (ctx: any) => {
      const methodItem = (route_81 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_81 as any).rateLimits?.GET ?? (route_81 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_81_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/media/tv/:id/similar",
    route_82.schema,
    async (ctx: any) => {
      const methodItem = (route_82 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_82 as any).rateLimits?.GET ?? (route_82 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_82_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/search/anime",
    route_83.schema,
    async (ctx: any) => {
      const methodItem = (route_83 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_83 as any).rateLimits?.GET ?? (route_83 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_83_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/search/books",
    route_84.schema,
    async (ctx: any) => {
      const methodItem = (route_84 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_84 as any).rateLimits?.GET ?? (route_84 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_84_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/search/characters",
    route_85.schema,
    async (ctx: any) => {
      const methodItem = (route_85 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_85 as any).rateLimits?.GET ?? (route_85 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_85_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/search/games",
    route_86.schema,
    async (ctx: any) => {
      const methodItem = (route_86 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_86 as any).rateLimits?.GET ?? (route_86 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_86_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/search/manga",
    route_87.schema,
    async (ctx: any) => {
      const methodItem = (route_87 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_87 as any).rateLimits?.GET ?? (route_87 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_87_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/search/movies",
    route_88.schema,
    async (ctx: any) => {
      const methodItem = (route_88 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_88 as any).rateLimits?.GET ?? (route_88 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_88_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/search/music",
    route_89.schema,
    async (ctx: any) => {
      const methodItem = (route_89 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_89 as any).rateLimits?.GET ?? (route_89 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_89_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/search/people",
    route_90.schema,
    async (ctx: any) => {
      const methodItem = (route_90 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_90 as any).rateLimits?.GET ?? (route_90 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_90_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/search/studios",
    route_91.schema,
    async (ctx: any) => {
      const methodItem = (route_91 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_91 as any).rateLimits?.GET ?? (route_91 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_91_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/search/tv",
    route_92.schema,
    async (ctx: any) => {
      const methodItem = (route_92 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_92 as any).rateLimits?.GET ?? (route_92 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_92_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/recommendations/:id",
    route_93.schema,
    async (ctx: any) => {
      const methodItem = (route_93 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_93 as any).rateLimits?.DELETE ?? (route_93 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_93_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/recommendations/:id/vote",
    route_94.schema,
    async (ctx: any) => {
      const methodItem = (route_94 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_94 as any).rateLimits?.POST ?? (route_94 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_94_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/recommendations/:type/:id",
    route_95.schema,
    async (ctx: any) => {
      const methodItem = (route_95 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_95 as any).rateLimits?.GET ?? (route_95 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_95_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/recommendations",
    route_96.schema,
    async (ctx: any) => {
      const methodItem = (route_96 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_96 as any).rateLimits?.POST ?? (route_96 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_96_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/reviews/:type/:id",
    route_97.schema,
    async (ctx: any) => {
      const methodItem = (route_97 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_97 as any).rateLimits?.GET ?? (route_97 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_97_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/reviews/:type/:id",
    route_97.schema,
    async (ctx: any) => {
      const methodItem = (route_97 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_97 as any).rateLimits?.POST ?? (route_97 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_97_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .delete(
    "/reviews/:type/:id",
    route_97.schema,
    async (ctx: any) => {
      const methodItem = (route_97 as any).DELETE;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_97 as any).rateLimits?.DELETE ?? (route_97 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_97_DELETE", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .patch(
    "/reviews/:type/:id",
    route_97.schema,
    async (ctx: any) => {
      const methodItem = (route_97 as any).PATCH;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_97 as any).rateLimits?.PATCH ?? (route_97 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_97_PATCH", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .post(
    "/reviews/:type/:id/vote",
    route_98.schema,
    async (ctx: any) => {
      const methodItem = (route_98 as any).POST;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_98 as any).rateLimits?.POST ?? (route_98 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_98_POST", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  )
  .get(
    "/user/:username/reviews",
    route_99.schema,
    async (ctx: any) => {
      const methodItem = (route_99 as any).GET;
      const handler = typeof methodItem === "function" ? methodItem : methodItem?.handler;
      const rateLimitConfig = methodItem?.rateLimit ?? (route_99 as any).rateLimits?.GET ?? (route_99 as any).rateLimit;
      const limiter = rateLimitConfig ? getRouteLimiter("route_99_GET", rateLimitConfig) : null;
      ctx.cacheKeys = globalCacheKeyStorage;
      return executeWithRequestLogs(ctx, handler, limiter) as any;
    }
  );

export type App = typeof routes;
