/**
 * nestia.config.ts — drop into the project root, next to tsconfig.json.
 *
 * This template covers every option in INestiaConfig with comments explaining
 * when to flip each one. Most projects only need `input`, `output`, `swagger`,
 * and (when shipping the SDK as a package) `distribute`. The rest are commented
 * out — uncomment as the project's needs grow.
 *
 * Bootstrap a minimal version with: `npx nestia init`
 */
import type { INestiaConfig } from "@nestia/sdk";
import { NestFactory } from "@nestjs/core";
// import { FastifyAdapter } from "@nestjs/platform-fastify";

import { AppModule } from "./src/AppModule";

const NESTIA_CONFIG: INestiaConfig = {
  /**
   * Where the controllers live.
   *
   * The function form (used here) is the most accurate — it boots the same
   * module graph the runtime uses, including any setGlobalPrefix or versioning.
   * For Fastify, pass `new FastifyAdapter()` to NestFactory.create().
   *
   * Alternatives (faster but less accurate):
   *   input: ["src/**\/*.controller.ts"]
   *   input: { include: ["src/**\/*.controller.ts"], exclude: ["**\/*.spec.ts"] }
   */
  input: async () => {
    const app = await NestFactory.create(AppModule);
    // app.setGlobalPrefix("api");
    // app.enableVersioning({ type: VersioningType.URI, prefix: "v" });
    return app;
  },

  /**
   * Where the generated SDK is written.
   * Conventional value: "src/api". The directory will be (re)created on every
   * `npx nestia sdk` run — don't store hand-written code in it.
   */
  output: "src/api",

  /**
   * Optional: Swagger document generation.
   * Remove this block entirely if Swagger is not needed.
   */
  swagger: {
    output: "packages/api/swagger.json",
    openapi: "3.1", // "3.0" or "2.0" if a downstream consumer requires it
    info: {
      title: "My API",
      version: "1.0.0",
      description: "Auto-generated by @nestia/sdk.",
    },
    servers: [
      { url: "http://localhost:3000", description: "Local dev" },
      // { url: "https://api.example.com", description: "Production" },
    ],
    // Uncomment to declare auth schemes; reference them via @security JSDoc tags on routes.
    // security: {
    //   bearer: { type: "http", scheme: "bearer" },
    // },
    // Uncomment to attach descriptions to tags; otherwise tag names alone are used.
    // tags: [
    //   { name: "articles", description: "Article CRUD operations." },
    // ],
    // Splits each query DTO field into its own OpenAPI parameter (recommended).
    decompose: true,
    // Custom operation IDs. Default: `<class>_<method>`.
    // operationId: ({ class: c, function: f }) => `${c.replace(/Controller$/, "")}.${f}`,
  },

  /**
   * Optional: scaffold a publishable npm package containing the SDK.
   * Conventional value: "packages/api" (then `cd packages/api && npm publish`).
   * Remove if the SDK stays internal to this repo.
   */
  distribute: "packages/api",

  /**
   * Optional: bake a mockup simulator into the SDK.
   *
   * With `simulate: true`, frontend code can do:
   *
   *   const connection = { host: "...", simulate: true };
   *
   * and the SDK runs locally — validating inputs with typia.assert<T>(), returning
   * random valid responses with typia.random<T>(). Lets the frontend start before
   * the backend is implemented.
   */
  simulate: true,

  /**
   * Optional: directory for auto-generated E2E test scaffolds.
   *
   * Run `npx nestia e2e` to populate it. Each route gets a `test_api_<...>.ts` file
   * with the SDK call wired up — the developer adds the assertions.
   */
  e2e: "test/features/api",

  /**
   * Optional: return IPropagation<T> from SDK functions instead of throwing on non-2xx.
   *
   * With `propagate: true`, every SDK function resolves to a discriminated union
   * keyed by status code. The error branches come from @TypedException decorators
   * on the route. Useful when the client wants exhaustive type-checked error
   * handling without try/catch.
   */
  // propagate: true,

  /**
   * Optional: clone DTO types into the SDK.
   *
   * Set this when the controllers return ORM-coupled types (Prisma models, TypeORM
   * entities) directly, and the SDK is published as a package — without `clone: true`
   * the SDK consumers would have to install Prisma/TypeORM transitively.
   */
  // clone: true,

  /**
   * Whether to wrap DTO types in Primitive<T> in the SDK (default: true).
   *
   * Primitive<T> strips methods, converts Date to string, etc. — reflecting what
   * actually crosses JSON. Turn off only if all DTOs are already plain interfaces
   * and the wrapping is more annoying than helpful.
   */
  // primitive: false,

  /**
   * Optional: typia.assert<T>() SDK arguments at runtime.
   * Slows compile slightly; catches type errors at the client.
   */
  // assert: true,

  /**
   * Optional: typia.assertStringify<T>() request bodies in the SDK.
   * ~10x faster than JSON.stringify, validates while serializing.
   */
  // json: true,
};

export default NESTIA_CONFIG;
