import { tags } from "typia";

/**
 * Setup data returned to the user when initializing TOTP Authenticator enrollment.
 */
export interface ITotpSetupResponse {
  /**
   * Base32 TOTP secret key for manual entry.
   *
   * @example "JBSWY3DPEHPK3PXP"
   */
  readonly secret: string;

  /**
   * Standard `otpauth://` URI.
   *
   * @example "otpauth://totp/IRIS:alice%40example.com?secret=JBSWY3DPEHPK3PXP&issuer=IRIS"
   */
  readonly otpauthUrl: string;

  /**
   * Base64 data URL representing the QR code image for scanning.
   *
   * @example "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
   */
  readonly qrCodeDataUrl: string;
}

/**
 * Request payload for confirming initial TOTP setup with a code from the authenticator app.
 */
export interface ITotpEnableRequest {
  /**
   * 6-digit numeric token generated by the authenticator app.
   *
   * @example "123456"
   */
  readonly code: string & tags.Pattern<"^\\d{6}$">;
}

/**
 * Response payload returned upon successful TOTP enablement, including emergency backup codes.
 */
export interface ITotpEnableResponse {
  /**
   * Whether TOTP is now active.
   *
   * @example true
   */
  readonly success: boolean;

  /**
   * List of 10 single-use emergency backup codes (display once to the user).
   *
   * @example ["A1B2-C3D4", "E5F6-G7H8", "I9J0-K1L2"]
   */
  readonly backupCodes: readonly string[];
}

/**
 * Request payload for disabling TOTP (requires password confirmation).
 */
export interface ITotpDisableRequest {
  /**
   * Current account password for security confirmation.
   *
   * @example "SuperSecretPass123!"
   */
  readonly password: string & tags.MinLength<1>;
}

/**
 * Request payload for toggling Email MFA.
 */
export interface IEmailMfaToggleRequest {
  /**
   * Whether Email MFA should be enabled (`true`) or disabled (`false`).
   *
   * @example true
   */
  readonly enabled: boolean;
}

/**
 * Request payload for requesting an Email verification code during login.
 */
export interface IMfaSendEmailCodeRequest {
  /**
   * Short-lived MFA challenge ticket received from `/auth/login`.
   *
   * @example "mfa_9a8b7c6d5e4f3a2b"
   */
  readonly mfaTicket: string & tags.MinLength<10>;
}

/**
 * Request payload for verifying an MFA challenge code (TOTP, Email OTP, or Backup Code).
 */
export interface IMfaVerifyRequest {
  /**
   * Short-lived MFA challenge ticket received from `/auth/login`.
   *
   * @example "mfa_9a8b7c6d5e4f3a2b"
   */
  readonly mfaTicket: string & tags.MinLength<10>;

  /**
   * MFA strategy being verified.
   *
   * @example "totp"
   */
  readonly mfaType: "totp" | "email" | "backup_code";

  /**
   * Verification code (6-digit numeric OTP or 8-12 character backup code).
   *
   * @example "123456"
   */
  readonly code: string & tags.MinLength<6> & tags.MaxLength<32>;
}

/**
 * Response payload containing newly generated emergency backup codes.
 */
export interface IBackupCodesRegenerateResponse {
  /**
   * Fresh list of single-use emergency backup codes.
   *
   * @example ["A1B2-C3D4", "E5F6-G7H8", "I9J0-K1L2"]
   */
  readonly backupCodes: readonly string[];
}
