/**
 * @packageDocumentation
 * @module api.functional.auth.passkey.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { IPasskeySummary } from "../../../../../../apps/server/src/modules/IRIS-account/dtos/passkey.dto";

/**
 * Lists all passkeys registered on the authenticated user's account.
 *
 * @returns Array of passkey descriptors.
 *
 * @controller AuthPasskeyController.listPasskeys
 * @path GET /auth/passkey/list
 * @accessor api.functional.auth.passkey.list.listPasskeys
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listPasskeys(
  connection: IConnection,
): Promise<listPasskeys.Output> {
  return true === connection.simulate
    ? listPasskeys.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...listPasskeys.METADATA,
        template: listPasskeys.METADATA.path,
        path: listPasskeys.path(),
      });
}
export namespace listPasskeys {
  export type Output = Primitive<Array<IPasskeySummary>>;

  export const METADATA = {
    method: "GET",
    path: "/auth/passkey/list",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/passkey/list";
  export const random = (): Resolved<Primitive<Array<IPasskeySummary>>> =>
    typia.random<Primitive<Array<IPasskeySummary>>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
