/**
 * @packageDocumentation
 * @module api.functional.auth.passkey.verify_login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ILoginResponse } from "../../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";
import type { IPasskeyVerifyLoginRequest } from "../../../../../../apps/server/src/modules/IRIS-account/dtos/passkey.dto";

/**
 * Verifies WebAuthn assertion signature and logs in the user.
 *
 * @param body - Assertion response.
 * @returns Successful login session.
 * @throws 400 Malformed clientDataJSON.
 * @throws 401 Passkey verification failed or challenge expired.
 *
 * @controller AuthPasskeyController.verifyLogin
 * @path POST /auth/passkey/verify-login
 * @accessor api.functional.auth.passkey.verify_login.verifyLogin
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function verifyLogin(
  connection: IConnection,
  body: verifyLogin.Body,
): Promise<verifyLogin.Output> {
  return true === connection.simulate
    ? verifyLogin.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...verifyLogin.METADATA,
          template: verifyLogin.METADATA.path,
          path: verifyLogin.path(),
        },
        body,
      );
}
export namespace verifyLogin {
  export type Body = Primitive<IPasskeyVerifyLoginRequest>;
  export type Output = Primitive<ILoginResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/passkey/verify-login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/passkey/verify-login";
  export const random = (): Resolved<Primitive<ILoginResponse>> =>
    typia.random<Primitive<ILoginResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
