/**
 * @packageDocumentation
 * @module api.functional.auth.passkey
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ISuccessResponse } from "../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";

export * as login_options from "./login_options/index";
export * as verify_login from "./verify_login/index";
export * as register_options from "./register_options/index";
export * as register_verify from "./register_verify/index";
export * as list from "./list/index";

/**
 * Deletes a registered passkey.
 *
 * @param id - ID of the passkey to delete.
 * @returns Success acknowledgment.
 * @throws 404 Passkey not found.
 *
 * @controller AuthPasskeyController.deletePasskey
 * @path DELETE /auth/passkey/:id
 * @accessor api.functional.auth.passkey.deletePasskey
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deletePasskey(
  connection: IConnection,
  id: string,
): Promise<deletePasskey.Output> {
  return true === connection.simulate
    ? deletePasskey.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...deletePasskey.METADATA,
        template: deletePasskey.METADATA.path,
        path: deletePasskey.path(id),
      });
}
export namespace deletePasskey {
  export type Output = Primitive<ISuccessResponse>;

  export const METADATA = {
    method: "DELETE",
    path: "/auth/passkey/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/auth/passkey/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (): Resolved<Primitive<ISuccessResponse>> =>
    typia.random<Primitive<ISuccessResponse>>();
  export const simulate = (connection: IConnection, id: string): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random();
  };
}
