/**
 * @packageDocumentation
 * @module api.functional.auth.password.reset
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  IPasswordResetRequest,
  ISuccessResponse,
} from "../../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";

/**
 * Completes password reset using a valid recovery token.
 *
 * @param body - Reset token and new password.
 * @returns Success response.
 * @throws 400 Password reset token is invalid or has expired.
 *
 * @controller AuthController.resetPassword
 * @path POST /auth/password/reset
 * @accessor api.functional.auth.password.reset.resetPassword
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function resetPassword(
  connection: IConnection,
  body: resetPassword.Body,
): Promise<resetPassword.Output> {
  return true === connection.simulate
    ? resetPassword.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...resetPassword.METADATA,
          template: resetPassword.METADATA.path,
          path: resetPassword.path(),
        },
        body,
      );
}
export namespace resetPassword {
  export type Body = Primitive<IPasswordResetRequest>;
  export type Output = Primitive<ISuccessResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/password/reset",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/password/reset";
  export const random = (): Resolved<Primitive<ISuccessResponse>> =>
    typia.random<Primitive<ISuccessResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
