/**
 * @packageDocumentation
 * @module api.functional.auth.password.change
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type {
  IPasswordChangeRequest,
  ISuccessResponse,
} from "../../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";

/**
 * Changes the user's password and invalidates all existing active sessions.
 *
 * @param body - Current and new password.
 * @returns Success response.
 * @throws 401 Incorrect current password.
 * @throws 404 User not found.
 *
 * @controller AuthController.changePassword
 * @path POST /auth/password/change
 * @accessor api.functional.auth.password.change.changePassword
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function changePassword(
  connection: IConnection,
  body: changePassword.Body,
): Promise<changePassword.Output> {
  return true === connection.simulate
    ? changePassword.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...changePassword.METADATA,
          template: changePassword.METADATA.path,
          path: changePassword.path(),
        },
        body,
      );
}
export namespace changePassword {
  export type Body = Primitive<IPasswordChangeRequest>;
  export type Output = Primitive<ISuccessResponse>;

  export const METADATA = {
    method: "POST",
    path: "/auth/password/change",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/password/change";
  export const random = (): Resolved<Primitive<ISuccessResponse>> =>
    typia.random<Primitive<ISuccessResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
