/**
 * @packageDocumentation
 * @module api.functional.account.mfa.email.toggle
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator, PlainFetcher } from "@nestia/fetcher";
import type { Primitive, Resolved } from "typia";
import typia from "typia";

import type { ISuccessResponse } from "../../../../../../../apps/server/src/modules/IRIS-account/dtos/auth.dto";
import type { IEmailMfaToggleRequest } from "../../../../../../../apps/server/src/modules/IRIS-account/dtos/mfa.dto";

/**
 * Enables or disables Email MFA for the user.
 *
 * @param body - Enable/disable flag.
 * @returns Success acknowledgment.
 *
 * @controller AccountMfaController.toggleEmailMfa
 * @path POST /account/mfa/email/toggle
 * @accessor api.functional.account.mfa.email.toggle.toggleEmailMfa
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function toggleEmailMfa(
  connection: IConnection,
  body: toggleEmailMfa.Body,
): Promise<toggleEmailMfa.Output> {
  return true === connection.simulate
    ? toggleEmailMfa.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...toggleEmailMfa.METADATA,
          template: toggleEmailMfa.METADATA.path,
          path: toggleEmailMfa.path(),
        },
        body,
      );
}
export namespace toggleEmailMfa {
  export type Body = Primitive<IEmailMfaToggleRequest>;
  export type Output = Primitive<ISuccessResponse>;

  export const METADATA = {
    method: "POST",
    path: "/account/mfa/email/toggle",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/account/mfa/email/toggle";
  export const random = (): Resolved<Primitive<ISuccessResponse>> =>
    typia.random<Primitive<ISuccessResponse>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
